### ISSUE TITLE
Add Endpoints

### ISSUE THREAD

**Issue by chaos-baum** [xiffy/lfm#2]
Hi, really enjoy your service!

I was thinking that maybe a rss endpoint for the weekly/monthly/yearly reports would be nice. 
In addition also an endpoint for top artists / tracks / album would be nice, maybe even filterable by date. 

I think all these endpoints already exist in their api, so we would just need the rss templates.

**Comment by xiffy** [comment]
Nice thought.
Unfortunatly, only weekly stats are available according to this api documentation: https://www.last.fm/api/show/user.getTopAlbums (linkin to top albums, there are 4 weekly endpoints available, no monthly (paid subscribers only, no endpoint in the api), but some others are do-able, and maybe the weekly endpoints give an option to name the week.

[some minutes of quick scanning the docs.] Aha! Yes we could get a from and to date for charts, and this service: https://www.last.fm/api/show/user.getWeeklyChartList tells us between which dates the lists should be available.

I'll ponder about a possible implementation.

**Comment by xiffy** [comment]
so top- artist, track, albums can be fetched by: _overall | 7day | 1month | 3month | 6month | 12month_
and with the weekly endpoints could be fiddled, like calling 4 weeks, aggregate to resemble a month. 
I'' run some tests this weekend if i could produce something usable.

**Comment by xiffy** [comment]
currently live:
top artists and top tracks, both with possible period argument. See https://lfm.xiffy.nl/

**Comment by chaos-baum** [comment]
Just checked it out. Very cool!
